### ISSUE TITLE
云函数调用另一个云函数用户登录状态丢失～～

### ISSUE THREAD

**Issue by medz** [TencentCloudBase/node-sdk#11]
如题

**Comment by Mrjing** [comment]
这里的用户登录态丢失是指？可以详细描述一下吗😂

**Comment by medz** [comment]
@Mrjing 云函数开启 Http 鉴权，通过 URL 调用，这个云函数能接收当前鉴权的用户登陆状态，但是这个云函数调用另一个，另一个云函数就没有用户状态

**Comment by Mrjing** [comment]
这里你在C端调用了 云函数A ，然后云函数A中有用户状态，然后A 再调云函数 B，B中没有用户态，原因是，云函数本身已经是管理员的权限了， 你可以在云函数A中 直接把用户相关信息 作为参数， 直接传给云函数B使用的
