### ISSUE TITLE
init env - 为什么env不是string | Symbol?

### ISSUE THREAD

**Issue by chenliang0571** [TencentCloudBase/node-sdk#12]
根据ICloudBaseConfig的定义`env`是`string`，`envName`才是`string | Symbol`。
```Javascript
export interface ICloudBaseConfig extends IKeyValue {
    debug?: boolean;
    timeout?: number;
    isHttp?: boolean;
    secretId?: string;
    secretKey?: string;
    envName?: string | Symbol;
    env?: string;
    sessionToken?: string;
    serviceUrl?: string;
    headers?: any;
    proxy?: string;
    version?: string;
    credentials?: ICredentialsInfo;
    throwOnCode?: boolean;
    forever?: boolean;
}
```
官方的初始化教程是`env: tcb.SYMBOL_CURRENT_ENV`
https://docs.cloudbase.net/api-reference/server/node-sdk/initialization.html#init
```
//获取执行当前云函数的环境
const currentEnv = tcb.SYMBOL_CURRENT_ENV

//云函数下指定环境为当前的执行环境
const app = tcb.init({
  env: currentEnv
})
```

使用后会出错，这里为什么env不是string | Symbol ？
```
(property) ICloudBaseConfig.env?: string
Type 'symbol' is not assignable to type 'string'.ts(2322)
index.d.ts(17, 5): The expected type comes from property 'env' which is declared here on type 'ICloudBaseConfig'
```

如果使用`envName: tcb.SYMBOL_CURRENT_ENV`，似乎无效，log会显示未指定。
`当前未指定env，将默认使用第一个创建的环境！`

**Comment by chenliang0571** [comment]
版本
"@cloudbase/node-sdk": "^2.2.3"

**Comment by Mrjing** [comment]
env的types定义我们会修复一下，另外使用envName: tcb.SYMBOL_CURRENT_ENV 无效的这个问题，当前是在云函数环境中使用的么？

**Comment by chenliang0571** [comment]
> env的types定义我们会修复一下，另外使用envName: tcb.SYMBOL_CURRENT_ENV 无效的这个问题，当前是在云函数环境中使用的么？

是的，因为这里使用的是`envName`，所以出现了`当前未指定env，将默认使用第一个创建的环境！`。
换为`env`后就好了。

**Comment by Mrjing** [comment]
嗯， envName这个类型提示之后会屏蔽掉，env是正确的用法

**Comment by Mrjing** [comment]
close
