### ISSUE TITLE
api缺少checkCollectionExists

### ISSUE THREAD

**Issue by DaZiYuan** [TencentCloudBase/node-sdk#14]
现在仅有`createCollection` 感觉很鸡肋。无法检测集合是否已创建。
既然管理端sdk进入维护状态，应该把`checkCollectionExists`也迁移过来

**Comment by Mrjing** [comment]
管理端sdk 仍在迭代中 😂  ，checkCollectionExists 也是属于管理端sdk 设计上支持的能力

**Comment by DaZiYuan** [comment]
https://docs.cloudbase.net/api-reference/server/node-sdk/packageUpgrade.html

这里写的 ```tcb-admin-node 会处于维护阶段，不会新增特性。```，给人的感觉就是要放弃的意思.....

**Comment by Mrjing** [comment]
tcb-admin-node 不是管理端sdk，它相当于旧版本的 node-sdk ，确实不再迭代了，我说的管理端SDK是指 @cloudbase/manager-node，https://docs.cloudbase.net/api-reference/manager/node/database.html#checkcollectionexists

**Comment by DaZiYuan** [comment]
好吧，但是即使是这样，服务端sdk只提供createCollection 任然很奇怪，想不到应用场景，难道不是都应该先检查再创建么

**Comment by Mrjing** [comment]
嗯，实际上可以直接用manager sdk的接口来完成创建集合的逻辑，node-sdk上的这个接口是早期设计上留下来的，这个接口确实是偏管理端的能力

**Comment by DaZiYuan** [comment]
嗯看错文档，以为要统一。使用管理包算了
