### ISSUE TITLE
更好的 typescript 支持

### ISSUE THREAD

**Issue by elvinn** [TencentCloudBase/node-sdk#9]
`@cloudbase/node-sdk` 依赖了 `@cloudbase/database`，但是却没有将相应的类型导出，希望也能进行导出，从而可以直接从 `@cloudbase/node-sdk` 中获取类型。

``` js
// 目前代码
import tcb from '@cloudbase/node-sdk';
import { CollectionReference } from '@cloudbase/database';

const collectionCache = new Map<string, CollectionReference>();
```

``` js
// 期望优化后的代码
import tcb from '@cloudbase/node-sdk';

const collectionCache = new Map<string, tcb.CollectionReference>();
```

**Comment by medz** [comment]
远不止如此～很多本该导出的 types 都没有导出。。有种他们开发者不会 typescript 硬用的感觉，。，。

**Comment by Mrjing** [comment]
嗯，db类型定义在 node-sdk 里确实没有很好的导出，我们会检查一下SDK内所有的类型定义问题 ，下个版本修复掉，谢谢反馈。

**Comment by Mrjing** [comment]
近期处理了node-sdk里的一些types 定义问题，可以安装@cloudbase/node-sdk@2.4.2-beta 这个版本试用下呢 @elvinn @medz
